# Generated by Django 3.0.8 on 2020-08-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontEndSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='photos/frontend/logo/')),
                ('text_logo', models.CharField(blank=True, max_length=20, null=True)),
                ('footer', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'FrontEndSetting',
                'verbose_name_plural': 'FrontEndSettings',
                'db_table': 'frontendsettings',
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewaySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, max_length=500, null=True)),
                ('store_pass', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'PaymentGatewaySetting',
                'verbose_name_plural': 'PaymentGatewaySettings',
                'db_table': 'paymentgatewaysettings',
            },
        ),
        migrations.CreateModel(
            name='StaticFileSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_use_aws', models.BooleanField(default=False)),
                ('aws_groupname', models.CharField(blank=True, max_length=200, null=True)),
                ('aws_username', models.CharField(blank=True, max_length=200, null=True)),
                ('aws_access_key_id', models.CharField(blank=True, max_length=200, null=True)),
                ('aws_secret_access_key', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'StaticFileSetting',
                'verbose_name_plural': 'StaticFileSettings',
                'db_table': 'staticfilesettings',
            },
        ),
    ]
