# Generated by Django 3.0.8 on 2021-02-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendsettings',
            name='is_teacher_register',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='frontendsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/frontend/logo/'),
        ),
    ]
