# Generated by Django 3.0.8 on 2021-02-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0008_testimonial_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='title',
            new_name='name',
        ),
    ]
