# Generated by Django 3.0.8 on 2021-02-11 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='ans',
            field=models.CharField(choices=[('choice_one', 'One'), ('choice_two', 'Two'), ('choice_three', 'Three'), ('choice_four', 'Four')], max_length=12),
        ),
        migrations.CreateModel(
            name='QuizExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(choices=[('choice_one', 'One'), ('choice_two', 'Two'), ('choice_three', 'Three'), ('choice_four', 'Four')], max_length=12)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_exam', to='quizapp.QuizQuestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'Exam',
            },
        ),
    ]
