# Generated by Django 3.0.8 on 2021-02-19 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_auto_20210219_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
