# Generated by Django 3.0.8 on 2020-07-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
