# Generated by Django 3.0.8 on 2020-07-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0003_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='biling_profile',
        ),
    ]
