# Generated by Django 3.0.8 on 2020-07-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200720_1704'),
        ('billings', '0004_remove_transaction_biling_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='products',
            field=models.ManyToManyField(blank=True, to='courses.Course'),
        ),
    ]
