# Generated by Django 3.0.8 on 2020-09-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_is_published'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='photos/quiz/%Y-%m-%d/')),
                ('choice_one', models.CharField(max_length=250)),
                ('choice_two', models.CharField(max_length=250)),
                ('choice_three', models.CharField(max_length=250)),
                ('choice_four', models.CharField(max_length=250)),
                ('ans', models.CharField(choices=[('choice_one', 'One'), ('choice_two', 'Two'), ('choice_three', 'Three'), ('choice_four', 'Four')], max_length=300)),
            ],
            options={
                'verbose_name': 'QuizQuestion',
                'verbose_name_plural': 'QuizQuestions',
            },
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='choice_four',
            new_name='descriptions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='ans',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='choice_one',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='choice_three',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='choice_two',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='courseref', to='courses.Course'),
            preserve_default=False,
        ),
    ]
