# Generated by Django 3.0.8 on 2020-07-26 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollcouese',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
    ]
