# Generated by Django 3.0.8 on 2020-07-08 03:41

import accounts.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.manager.CustomUserManager()),
            ],
        ),
    ]
