# Generated by Django 3.0.8 on 2020-07-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lesson',
            table='Lessons',
        ),
    ]
