# Generated by Django 3.0.8 on 2020-07-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200709_1538'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='lessons',
        ),
        migrations.AlterModelTable(
            name='lessoncontent',
            table='lessonsContents',
        ),
    ]
