# Generated by Django 3.0.8 on 2020-07-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='video_link',
            field=models.URLField(max_length=500),
        ),
    ]
