# Generated by Django 3.0.8 on 2020-07-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200720_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='a', unique=True),
            preserve_default=False,
        ),
    ]
