# Generated by Django 3.0.8 on 2020-07-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200720_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='video_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
