# Generated by Django 3.0.8 on 2020-08-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200730_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='title',
            new_name='curriculum_title',
        ),
    ]
